<?php

namespace Database\Seeders;

use App\Domain\Financial\Models\PKWiUClassification;
use Illuminate\Database\Seeder;

class PKWiUClassificationSeeder extends Seeder
{
    public function run(): void
    {
        $classifications = [
            // SECTION A: PRODUCTS OF AGRICULTURE, FORESTRY AND FISHING
            [
                'code'        => '01.00.00.0',
                'parent_code' => null,
                'name'        => 'Produkty rolne, łowieckie i związane z nimi usługi',
                'description' => 'Produkty rolnictwa, łowiectwa i usługi związane z produkcją rolną',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '01.11.00.0',
                'parent_code' => '01.00.00.0',
                'name'        => 'Zboża',
                'description' => 'Produkty zbożowe',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '01.11.10.0',
                'parent_code' => '01.11.00.0',
                'name'        => 'Pszenica',
                'description' => 'Pszenica i produkty pochodne',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '01.11.11.0',
                'parent_code' => '01.11.10.0',
                'name'        => 'Pszenica twarda',
                'description' => 'Pszenica twarda do produkcji przemysłowej',
                'level'       => 4,
                'is_active'   => true,
            ],
            [
                'code'        => '01.11.12.0',
                'parent_code' => '01.11.10.0',
                'name'        => 'Pszenica zwyczajna',
                'description' => 'Pszenica zwyczajna do celów spożywczych',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION B: MINING AND QUARRYING
            [
                'code'        => '05.00.00.0',
                'parent_code' => null,
                'name'        => 'Węgiel i lignit',
                'description' => 'Węgiel kamienny i brunatny',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '05.10.00.0',
                'parent_code' => '05.00.00.0',
                'name'        => 'Węgiel kamienny',
                'description' => 'Węgiel kamienny i antracyt',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '05.10.10.0',
                'parent_code' => '05.10.00.0',
                'name'        => 'Węgiel kamienny - antracyt',
                'description' => 'Antracyt wysokiej jakości',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '05.10.11.0',
                'parent_code' => '05.10.10.0',
                'name'        => 'Antracyt surowy',
                'description' => 'Antracyt nieprzetworzone',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION C: MANUFACTURING
            [
                'code'        => '10.00.00.0',
                'parent_code' => null,
                'name'        => 'Produkty przemysłu spożywczego',
                'description' => 'Artykuły spożywcze',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '10.11.00.0',
                'parent_code' => '10.00.00.0',
                'name'        => 'Mięso przetworzone i produkty mięsne',
                'description' => 'Mięso i wędliny',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '10.11.10.0',
                'parent_code' => '10.11.00.0',
                'name'        => 'Mięso wołowe',
                'description' => 'Mięso wołowe świeże i mrożone',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '10.11.11.0',
                'parent_code' => '10.11.10.0',
                'name'        => 'Mięso wołowe świeże',
                'description' => 'Świeże mięso wołowe',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION D: CONSTRUCTION
            [
                'code'        => '41.00.00.0',
                'parent_code' => null,
                'name'        => 'Budynki mieszkalne i niemieszkalnie',
                'description' => 'Obiekty budownictwa mieszkaniowego i komercyjnego',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '41.10.00.0',
                'parent_code' => '41.00.00.0',
                'name'        => 'Budynki mieszkalne',
                'description' => 'Budynki mieszkalne jednorodzinne i wielorodzinne',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '41.10.10.0',
                'parent_code' => '41.10.00.0',
                'name'        => 'Budynki mieszkalne jednorodzinne',
                'description' => 'Domy jednorodzinne',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '41.10.11.0',
                'parent_code' => '41.10.10.0',
                'name'        => 'Budynki mieszkalne jednorodzinne wolnostojące',
                'description' => 'Wolnostojące domy jednorodzinne',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION E: WHOLESALE AND RETAIL TRADE
            [
                'code'        => '46.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi handlu hurtowego, z wyjątkiem handlu pojazdami samochodowymi',
                'description' => 'Handel hurtowy towarami różnymi',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '46.11.00.0',
                'parent_code' => '46.00.00.0',
                'name'        => 'Usługi pośrednictwa w sprzedaży surowców rolnych',
                'description' => 'Pośrednictwo w handlu surowcami rolnymi',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '46.11.10.0',
                'parent_code' => '46.11.00.0',
                'name'        => 'Usługi pośrednictwa w sprzedaży zbóż',
                'description' => 'Pośrednictwo w handlu zbożem',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '46.11.11.0',
                'parent_code' => '46.11.10.0',
                'name'        => 'Usługi pośrednictwa w sprzedaży pszenicy',
                'description' => 'Pośrednictwo w handlu pszenicą',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION F: TRANSPORTATION AND STORAGE
            [
                'code'        => '49.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi transportu lądowego i rurociągowego',
                'description' => 'Transport lądowy osób i towarów',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '49.10.00.0',
                'parent_code' => '49.00.00.0',
                'name'        => 'Usługi transportu kolejowego',
                'description' => 'Transport kolejowy pasażerski i towarowy',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '49.10.10.0',
                'parent_code' => '49.10.00.0',
                'name'        => 'Usługi transportu kolejowego pasażerskiego',
                'description' => 'Transport kolejowy osób',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '49.10.11.0',
                'parent_code' => '49.10.10.0',
                'name'        => 'Usługi transportu kolejowego pasażerskiego międzymiastowego',
                'description' => 'Transport kolejowy dalekobieżny',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION G: ACCOMMODATION AND FOOD SERVICE
            [
                'code'        => '55.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi zakwaterowania',
                'description' => 'Usługi hotelowe i podobne',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '55.10.00.0',
                'parent_code' => '55.00.00.0',
                'name'        => 'Usługi hoteli i podobnych obiektów zakwaterowania',
                'description' => 'Usługi hotelowe',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '55.10.10.0',
                'parent_code' => '55.10.00.0',
                'name'        => 'Usługi hoteli',
                'description' => 'Usługi zakwaterowania w hotelach',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '55.10.11.0',
                'parent_code' => '55.10.10.0',
                'name'        => 'Usługi hoteli o wysokim standardzie',
                'description' => 'Usługi hoteli 4 i 5 gwiazdkowych',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION H: INFORMATION AND COMMUNICATION
            [
                'code'        => '58.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi wydawnicze',
                'description' => 'Publikacje i usługi wydawnicze',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '58.11.00.0',
                'parent_code' => '58.00.00.0',
                'name'        => 'Usługi wydawania książek',
                'description' => 'Publikacja książek',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '58.11.10.0',
                'parent_code' => '58.11.00.0',
                'name'        => 'Usługi wydawania książek drukowanych',
                'description' => 'Wydawanie książek w formie drukowanej',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '58.11.11.0',
                'parent_code' => '58.11.10.0',
                'name'        => 'Usługi wydawania książek naukowych',
                'description' => 'Publikacja literatury naukowej',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION I: FINANCIAL AND INSURANCE
            [
                'code'        => '64.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi finansowe, z wyłączeniem ubezpieczeń i funduszy emerytalnych',
                'description' => 'Usługi bankowe i finansowe',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '64.11.00.0',
                'parent_code' => '64.00.00.0',
                'name'        => 'Usługi banku centralnego',
                'description' => 'Usługi banku centralnego',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '64.11.10.0',
                'parent_code' => '64.11.00.0',
                'name'        => 'Usługi banku centralnego - polityka monetarna',
                'description' => 'Usługi związane z polityką monetarną',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '64.11.11.0',
                'parent_code' => '64.11.10.0',
                'name'        => 'Usługi banku centralnego - emisja waluty',
                'description' => 'Usługi emisji pieniądza',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION J: REAL ESTATE
            [
                'code'        => '68.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi związane z obsługą rynku nieruchomości',
                'description' => 'Usługi rynku nieruchomości',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '68.10.00.0',
                'parent_code' => '68.00.00.0',
                'name'        => 'Usługi kupna i sprzedaży nieruchomości własnych',
                'description' => 'Obrót nieruchomościami własnymi',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '68.10.10.0',
                'parent_code' => '68.10.00.0',
                'name'        => 'Usługi kupna i sprzedaży nieruchomości mieszkalnych własnych',
                'description' => 'Obrót nieruchomościami mieszkalnymi',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '68.10.11.0',
                'parent_code' => '68.10.10.0',
                'name'        => 'Usługi kupna i sprzedaży mieszkań własnych',
                'description' => 'Obrót mieszkaniami własnymi',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION K: PROFESSIONAL, SCIENTIFIC AND TECHNICAL ACTIVITIES
            [
                'code'        => '70.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi związane z działalnością firm centralnych (head offices); usługi doradztwa związane z zarządzaniem',
                'description' => 'Usługi zarządzania i doradztwa',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '70.10.00.0',
                'parent_code' => '70.00.00.0',
                'name'        => 'Usługi firm centralnych (head offices)',
                'description' => 'Usługi central przedsiębiorstw',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '70.10.10.0',
                'parent_code' => '70.10.00.0',
                'name'        => 'Usługi firm centralnych',
                'description' => 'Usługi zarządzania grupami przedsiębiorstw',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '70.10.11.0',
                'parent_code' => '70.10.10.0',
                'name'        => 'Usługi strategiczne firm centralnych',
                'description' => 'Usługi planowania strategicznego',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION L: PROFESSIONAL SERVICES
            [
                'code'        => '71.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi związane z architekturą i inżynierią; techniczne usługi badawcze i analityczne',
                'description' => 'Usługi architektoniczne i inżynierskie',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '71.11.00.0',
                'parent_code' => '71.00.00.0',
                'name'        => 'Usługi architektoniczne',
                'description' => 'Usługi projektowania architektonicznego',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '71.11.10.0',
                'parent_code' => '71.11.00.0',
                'name'        => 'Usługi architektoniczne dla budynków',
                'description' => 'Projektowanie architektoniczne budynków',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '71.11.11.0',
                'parent_code' => '71.11.10.0',
                'name'        => 'Usługi architektoniczne dla budynków mieszkalnych',
                'description' => 'Projektowanie budynków mieszkalnych',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION M: ADMINISTRATIVE AND SUPPORT SERVICES
            [
                'code'        => '77.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi wynajmu i dzierżawy',
                'description' => 'Usługi leasingu i wynajmu',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '77.11.00.0',
                'parent_code' => '77.00.00.0',
                'name'        => 'Usługi wynajmu i dzierżawy samochodów osobowych',
                'description' => 'Wynajem samochodów osobowych',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '77.11.10.0',
                'parent_code' => '77.11.00.0',
                'name'        => 'Usługi wynajmu samochodów osobowych',
                'description' => 'Wynajem aut osobowych',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '77.11.11.0',
                'parent_code' => '77.11.10.0',
                'name'        => 'Usługi wynajmu samochodów osobowych krótkoterminowego',
                'description' => 'Wynajem samochodów do 30 dni',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION N: EDUCATION
            [
                'code'        => '85.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi edukacyjne',
                'description' => 'Usługi kształcenia i szkolenia',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '85.10.00.0',
                'parent_code' => '85.00.00.0',
                'name'        => 'Usługi edukacyjne na poziomie przedszkolnym',
                'description' => 'Usługi edukacji przedszkolnej',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '85.10.10.0',
                'parent_code' => '85.10.00.0',
                'name'        => 'Usługi edukacyjne przedszkolne',
                'description' => 'Usługi wychowania przedszkolnego',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '85.10.11.0',
                'parent_code' => '85.10.10.0',
                'name'        => 'Usługi edukacyjne przedszkolne publiczne',
                'description' => 'Usługi publicznych przedszkoli',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION O: HEALTH AND SOCIAL WORK
            [
                'code'        => '86.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi związane z działalnością w zakresie ochrony zdrowia ludzkiego',
                'description' => 'Usługi medyczne i zdrowotne',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '86.10.00.0',
                'parent_code' => '86.00.00.0',
                'name'        => 'Usługi szpitalne',
                'description' => 'Usługi leczenia szpitalnego',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '86.10.10.0',
                'parent_code' => '86.10.00.0',
                'name'        => 'Usługi szpitalne ogólne',
                'description' => 'Usługi szpitali ogólnych',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '86.10.11.0',
                'parent_code' => '86.10.10.0',
                'name'        => 'Usługi szpitalne - chirurgia',
                'description' => 'Usługi chirurgiczne szpitalne',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION P: ARTS, ENTERTAINMENT AND RECREATION
            [
                'code'        => '90.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi twórcze, artystyczne i rozrywkowe',
                'description' => 'Usługi kultury i rozrywki',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '90.01.00.0',
                'parent_code' => '90.00.00.0',
                'name'        => 'Usługi związane z działalnością sceniczną',
                'description' => 'Usługi teatralne i sceniczne',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '90.01.10.0',
                'parent_code' => '90.01.00.0',
                'name'        => 'Usługi związane z działalnością teatralną',
                'description' => 'Usługi teatralne',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '90.01.11.0',
                'parent_code' => '90.01.10.0',
                'name'        => 'Usługi teatralne dramatyczne',
                'description' => 'Usługi teatru dramatycznego',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION Q: OTHER SERVICES
            [
                'code'        => '95.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi naprawy komputerów, artykułów osobistych i artykułów użytku domowego',
                'description' => 'Usługi napraw różnych przedmiotów',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '95.11.00.0',
                'parent_code' => '95.00.00.0',
                'name'        => 'Usługi naprawy komputerów i urządzeń peryferyjnych',
                'description' => 'Usługi naprawy sprzętu komputerowego',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '95.11.10.0',
                'parent_code' => '95.11.00.0',
                'name'        => 'Usługi naprawy komputerów stacjonarnych',
                'description' => 'Naprawa komputerów PC',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '95.11.11.0',
                'parent_code' => '95.11.10.0',
                'name'        => 'Usługi naprawy komputerów stacjonarnych - sprzęt',
                'description' => 'Naprawa hardware komputerów PC',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION R: INFORMATION TECHNOLOGY
            [
                'code'        => '62.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi związane z oprogramowaniem komputerowym',
                'description' => 'Programowanie, doradztwo informatyczne i działalność powiązana',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.00.0',
                'parent_code' => '62.00.00.0',
                'name'        => 'Usługi programowania komputerowego',
                'description' => 'Tworzenie oprogramowania komputerowego',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.10.0',
                'parent_code' => '62.01.00.0',
                'name'        => 'Usługi programowania aplikacji',
                'description' => 'Projektowanie i tworzenie aplikacji',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.11.0',
                'parent_code' => '62.01.10.0',
                'name'        => 'Usługi programowania aplikacji internetowych',
                'description' => 'Tworzenie aplikacji webowych i mobilnych',
                'level'       => 4,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.12.0',
                'parent_code' => '62.01.10.0',
                'name'        => 'Usługi programowania aplikacji desktopowych',
                'description' => 'Tworzenie aplikacji desktopowych',
                'level'       => 4,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.20.0',
                'parent_code' => '62.01.00.0',
                'name'        => 'Usługi programowania systemów',
                'description' => 'Programowanie systemów operacyjnych i oprogramowania systemowego',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '62.01.21.0',
                'parent_code' => '62.01.20.0',
                'name'        => 'Usługi programowania systemów operacyjnych',
                'description' => 'Tworzenie systemów operacyjnych',
                'level'       => 4,
                'is_active'   => true,
            ],

            // More IT services
            [
                'code'        => '62.02.00.0',
                'parent_code' => '62.00.00.0',
                'name'        => 'Usługi doradztwa informatycznego',
                'description' => 'Doradztwo w zakresie informatyki',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '62.02.10.0',
                'parent_code' => '62.02.00.0',
                'name'        => 'Usługi doradztwa w zakresie systemów informatycznych',
                'description' => 'Doradztwo systemowe IT',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '62.02.11.0',
                'parent_code' => '62.02.10.0',
                'name'        => 'Usługi doradztwa w zakresie architektury IT',
                'description' => 'Doradztwo architektoniczne IT',
                'level'       => 4,
                'is_active'   => true,
            ],

            [
                'code'        => '62.03.00.0',
                'parent_code' => '62.00.00.0',
                'name'        => 'Usługi zarządzania urządzeniami informatycznymi',
                'description' => 'Zarządzanie infrastrukturą IT',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '62.03.10.0',
                'parent_code' => '62.03.00.0',
                'name'        => 'Usługi zarządzania sieciami komputerowymi',
                'description' => 'Administracja sieci IT',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '62.03.11.0',
                'parent_code' => '62.03.10.0',
                'name'        => 'Usługi zarządzania sieciami LAN',
                'description' => 'Administracja sieci lokalnych',
                'level'       => 4,
                'is_active'   => true,
            ],

            // SECTION S: LEGAL AND ACCOUNTING
            [
                'code'        => '69.00.00.0',
                'parent_code' => null,
                'name'        => 'Usługi prawne i księgowe',
                'description' => 'Usługi prawne, księgowe i audytorskie',
                'level'       => 1,
                'is_active'   => true,
            ],
            [
                'code'        => '69.10.00.0',
                'parent_code' => '69.00.00.0',
                'name'        => 'Usługi prawne',
                'description' => 'Usługi prawnicze i adwokackie',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '69.10.10.0',
                'parent_code' => '69.10.00.0',
                'name'        => 'Usługi prawne - prawo cywilne',
                'description' => 'Usługi prawne w zakresie prawa cywilnego',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '69.10.11.0',
                'parent_code' => '69.10.10.0',
                'name'        => 'Usługi prawne - prawo rodzinne',
                'description' => 'Usługi prawne w sprawach rodzinnych',
                'level'       => 4,
                'is_active'   => true,
            ],

            [
                'code'        => '69.20.00.0',
                'parent_code' => '69.00.00.0',
                'name'        => 'Usługi księgowe, prowadzenie dokumentacji księgowej i usługi audytorskie',
                'description' => 'Usługi księgowe i audytorskie',
                'level'       => 2,
                'is_active'   => true,
            ],
            [
                'code'        => '69.20.10.0',
                'parent_code' => '69.20.00.0',
                'name'        => 'Usługi księgowe',
                'description' => 'Prowadzenie ksiąg rachunkowych',
                'level'       => 3,
                'is_active'   => true,
            ],
            [
                'code'        => '69.20.11.0',
                'parent_code' => '69.20.10.0',
                'name'        => 'Usługi księgowe - księgi handlowe',
                'description' => 'Prowadzenie ksiąg rachunkowych przedsiębiorstw',
                'level'       => 4,
                'is_active'   => true,
            ],
        ];

        foreach ($classifications as $classification) {
            PKWiUClassification::create($classification);
        }
    }
}
