name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: sail
          POSTGRES_USER: sail
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, intl, pdo, pdo_pgsql, pgsql
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Copy .env and configure for CI
        run: |
          cp .env.example .env
          sed -i 's/DB_HOST=.*/DB_HOST=127.0.0.1/' .env
          sed -i 's/DB_PORT=.*/DB_PORT=5432/' .env
          sed -i 's/DB_DATABASE=.*/DB_DATABASE=sail/' .env
          sed -i 's/DB_USERNAME=.*/DB_USERNAME=sail/' .env
          sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=secret/' .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Run migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse

      - name: Run PHP-CS-Fixer
        run: composer csf || true