name: Laravel CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: saasbase_api
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
        options: >-
          --health-cmd="pg_isready -U root -d saasbase_api"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Set environment file
      run: cp .env.example .env

    - name: Build containers
      run: ./vendor/bin/sail build --no-cache

    - name: Start containers
      run: ./vendor/bin/sail up -d

    - name: Wait for database
      run: |
        until docker-compose exec pgsql pg_isready -U root -d saasbase_api; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done

    - name: Generate Laravel key
      run: ./vendor/bin/sail artisan key:generate

    - name: Run migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Run tests
      run: ./vendor/bin/sail artisan test --no-interaction

    - name: Run Larastan
      run: ./vendor/bin/sail vendor/bin/phpstan analyse

    - name: Run PHP CS Fixer
      run: ./vendor/bin/sail vendor/bin/php-cs-fixer fix --dry-run --diff