name: Deploy Laravel App

on:
  workflow_dispatch:  # ręczne uruchamianie z GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, pdo_mysql, tokenizer, xml, ctype, curl, dom, json, zip, openssl
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Archive project
        run: |
          mkdir deploy && \
          rsync -av --exclude=node_modules --exclude=vendor --exclude=.git ./ ./deploy

      - name: Upload to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: 'deploy/*'
          target: ${{ secrets.SSH_TARGET }}
          strip_components: 1

      - name: Run post-deploy commands on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export PATH="/home/madeyski/bin:$PATH"
            export PATH=/opt/alt/php83/usr/bin:$PATH
            cd ${{ secrets.SSH_TARGET }}
            composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
